export const MASTER_CACHE_KEYS = {
  DEPARTMENTS: 'DEPARTMENTS',
  DIVISIONS: 'DIVISIONS',
  DOCUMENT_TYPES: 'DOCUMENT_TYPES',
  SUB_DEPARTMENTS: 'SUB_DEPARTMENTS',
  BUSINESS_DOMAIN: 'BUSINESSDOMAINS'
} as const;


export const MASTER_DEFAULT_KEYS = {
  COMPANYID: '1'
} as const;
